{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- if $ingress.tls.enabled -}}
{{- if $ingress.tls.certificate.obtain -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jupyter-certificate
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  secretName: {{ template "tlsSecretName" $ }}
{{- with $ingress.tls.certificate.issuerRef }}
  issuerRef:
{{ toYaml . | indent 4 }}
{{- end }}
  dnsNames:
  - '{{ $ingress.domain }}'

{{- end -}}
{{- end -}}
{{- end -}}
