{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- if $ingress.tls.enabled -}}
{{- if $ingress.tls.certificate.obtain -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jupyter-certificate
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  secretName: {{ template "tlsSecretName" $ }}
{{- with $ingress.tls.certificate.issuerRef }}
  issuerRef:
{{ toYaml . | indent 4 }}
{{- end }}
  dnsNames:
  - '{{ $ingress.domain }}'

{{- end -}}
{{- end -}}
{{- end -}}
