{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-ingress
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ $ingress.domain }}
      secretName: {{ template "tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ $ingress.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: 80
{{- end -}}




