{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhub-ingress
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ $ingress.domain }}
      secretName: {{ template "tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ $ingress.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: proxy-public
                port:
                  number: 80
{{- end -}}




