dist: xenial

language: java

env:
  global:
     - APPNAME="jupyter"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
     - DEPLOYMENT_CONFIG_DIR="./.travis"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - NEXUS_USERNAME="travis-fairspace"
     - GCP_PROJECT="fairspace-207108"
     - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
     - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
     - RELEASE_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacedemocluster"
     - RELEASE_CLUSTER_NAME="fairspacedemocluster"
     - RELEASE_CLUSTER_ZONE="europe-west1-b"
     - GIT_TAG_FILES_OVERRIDE="charts/jupyter/Chart.yaml charts/jupyter/values.yaml projects/"

     # DOCKER_PASSWORD=
     - secure: "rINH6k9VSyv0N2vmle6xtT9gB3eSilSVsAmHRln4qkLTWHjLW7jjouehqFiRrdrnzFP+NIaAUdvP6ox3MhtZEFpW/pog0fZSMijpidlsHr9uCbsxhrGXjcZuzwtazaqQ/7+9RP+ofb7j6tPqt5HLCwn0pviom4qc9GztTahJwg9uNa6naiCWqIAkn7w5yqcPQZp6sgjcMYF+pKL6OQHywGp07qatozgqYkZGjtBD7QOKfNDNycVewtMQwI+CIno1/STk9kS0lECfIabETVYwt9Hzjk6811NFAwdKWVrgG+1MOU59uJC/CVbEpEfY/m1vWneWJ68L+DyYlcvzY2/pVC2A+T0L0YzhdiFCQC2xr81ODq7AQ0Y4KdYYrnewP8vJhD2zoJmfucdLpX0f93Q9k1oTd9I3sVbNK+J28N8PE6rc72t1uUA6Tzvht+OyJo5W+h4vm8zs0aWIFVLR6r0ShmindyBI0CFi6VbrvxMTNmzH1PM23oLCs3V66CTiHBBlmxEYud99zLt97/WW74DSju17wosPR9O1G2FlVPlRdhF1S7ELCN1WlFgwll7Ssy5Nk/jWqNK004+Ked3g676a38plphuOQLRKSFD7L1rh4tXli09/xjq8AXBjzyWVEUPHVFnKmDZMcQlixBVuO1FhpS6uFDLOzF6N2bfJkR8lwqI="

     # GITHUB_PASSWORD=....
     - secure: "Xq+sjWajNHGOq5wCqp7HfEVEWKttMaG4kgWJ9xYgWoD7fNK1KKmOg09FxOQ+hJI4J4MVW1KxvITPjMxBjrCROBsA3/bHvQAip5jHWV4+9xOV/0/Scl6nDGPZ/bhc9k4xQMq2DrfOGEDpFkj60Q17E6UvxEzPXUf/uiTZECDzwY5JulGEb9W+G6mwghRIxXHR5YSOXLEDlSu+Pn/rPc3tmGzRGlrOhlfAUTJSgfBV2wtbl53KL4aFnNyQWejc7734LwNGoEF8k+/IEM8PWjljR7a1dUEk7kOBiYQnnKcysAAwUPxbEhSwm28M8Tq8Rs8wDZ4/T0It/h7hy8B47kTxRnJ11QbgJgw2RWyq3wgeQiCaPNzh35ifVvPuIqIuCh+/XgQ0FAUmGEggDy99krGUdevuhv3g2bss4+bLXBsopwFGCHx4JJ478QLeBNgHCUsPmPYPvQc8J9AUVYJP4hR6U45y5FnSQYG3jWJiRojDY8w02pYoRK9aGttcDVtiL3ygPq41v6kkl//4yu5OxudS7xq+PRCBFN0PAYKizNr2iZ0yy3t9Z5MyhJaCoXzDsot8gLQXMdgZzRpqrrr7z52tp49qLMwNfKG7hGzeeZPDttth3qwle5u1MDup0q4wjiKj5+C+Vi/pCFtv3aCd+BJk+SxndioPAxm3r1kr9fzKeg8="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.cache

before_install:
  - export KUBE_CONFIG_ENC_KEY=$encrypted_f973873e750b_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_f973873e750b_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE" ; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=demo DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE" ; fi'
  - export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
  - source ./ci/setup_env.sh
  - 'if [[ "$SHOULD_RELEASE" ]] ; then export NEED_INTERNAL_HELM=1 ; fi'

jobs:
  include:
    - stage: build
      name: Build projects
      install:
      - ci/gcp/install.sh
      - ci/gcp/login.sh
      script:
      - .travis/build.sh projects/jupyterhub-hub
      - travis_wait 60 .travis/build.sh projects/jupyterhub-singleuser
    - stage: build
      cache: false
      name: Build helm charts
      install:
      - source charts/.travis/install.sh
      script:
      - charts/.travis/build.sh
    - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      cache: false
      stage: Versioning
      name: Set tag and update version
      script:
      - "ci/versioning/add_tag_to_git.sh"
      - "ci/versioning/set_next_version.sh"
    - stage: deploy
      cache: false
      if: branch IN (env(RELEASE_BRANCH), env(SNAPSHOT_BRANCH)) AND type != pull_request
      install:
        - source charts/.travis/install.sh
      script:
      - travis_wait ci/helm/deploy.sh $DEPLOY_TARGET

notifications:
  slack:
    rooms:
     - secure: "xujLTGH8Vsmm3HDs02/utkTjhV+X4PY0FLOPdDUg0A38RZRgtQ+TeKerZmVBivK958e1KzsL/wPhTdeOHm7DJnanvWs1Jkw3mgbrHcaiagGjBdaEW8F30f2nsIibGWGDqzUZd5ifXYSugLNpJSpdFkVOseuWhUyTwjwrb4Ec/U/D24YvZUwX/kfi/waly57iFkxIkhq2XwcvtJtEDAzsKPhfwL67giV0flbGvCRL4xkvHERSr/HsXJ+V2NCaJ/qiSm8NkWq5gsrIIRkAA3mBSDs5Uq1ozAEI/DxN752O/OReghvjd249AEhzqJ0Ezyu0BjX3kYR1bP3gKB2/wOrLv069tAchY+KQF2F6Jh3AzGAEh0x5ARMsOxDkJybz5nXwMoYwsUjN9zGo8j9egbzkkxoVTK+MOf34jaSn7UBwAT239MaXB4Er1srJEZRqIzXVH0qwc/lC1QYX0fA89a5GdFjyN7EhfdlsvIp93nn8sjgj9iYsqS3yQboGBOSou1sboR8U/RsjPQowOkqMv8XIcjTUodirKNiRSdo5Wf+nGl4fgc3AS7rJcRaPLpbAvJZtXJzi4tutbU293q2k+bfvXbNz8R4IG7R4+MGdMWeSWDd9A0UBHgQkpXkb8Oxzr7PDAyDvhVEI5KewVy1PnV7dMCeRzSASjXTfPNnYpgBMw3E="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
