dist: xenial

language: java

jdk:
- openjdk11

env:
  global:
     - NODE_VERSION="11.2.0"
     - APPNAME="jupyter"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="fairspace/build-scripts"
     - DEPLOYMENT_CONFIG_DIR="./.travis"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - NEXUS_USERNAME="travis-fairspace"
     - GCP_PROJECT="fairspace-207108"
     - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
     - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
     - RELEASE_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacedemocluster"
     - RELEASE_CLUSTER_NAME="fairspacedemocluster"
     - RELEASE_CLUSTER_ZONE="europe-west1-b"
     - GIT_TAG_FILES_OVERRIDE="charts/jupyter/Chart.yaml charts/jupyter/values.yaml projects/"

     # DOCKER_PASSWORD=
     - secure: "FJTXKY792rdmQZ6DLU5Dlm1W9ZAmFwBFWEJDO4dLJySBO/clUUV0OfRkNX4OaachKUlRCFGxYbXaXCioYtMTVg54aD1d+hjBO5azPzUiT8V2mz2w3MkvxsvnvivziJtcSfol/PNHQdEK8qZhZ9IwdCnQM9LQ3YVwv9tkNpR//qNmUjA4ZdcbQrBLQ63wm/UX2vCo4D3/J24TfCJrmlu9AyoIAqiFsRczsQGixQLRzeRgwH3yFgACZrMt42ySrx4rL+Yi3Ro/ZftY+YrZPRs+wrObh++OmdzjQWXH4KBg8HTFEIJXYMOVnpG0OSdNO7j7oVS8qVRHJmFAG0VHrmSIMMbjU+3js3SVJxtwXRc3xEPJzKzhtyqGaQa5mr3pI1Q8YingcsEBEpWOh9zXBzJm1uh7JhgTgcEbBwQl12/SctMjejyAFFqVHhlSAEzuDBwTkXLiv6z6sF+SUpww8I6eKmQrJUN1HVPm9+n1nsBy1j3PIM0RmTAf+jZCuAMDg0Dg0dlY/in/Jz1k/QuFDbJ4ura4YBBQ315UDoki5rucDi2poxq9YoAaMpMouso9ilAwOms3guVaU/rgOHZsmIPqv2ccH6FEoOh2UeEq3RCGbprLAj88f2rcGNPaHNWRkeek31c+TI9JZPmeL5eh5tJ64cN+feVVk8lbqNWtR9VHRrI="

     # GITHUB_PASSWORD=....
     - secure: "l8Eug1n9WfHuNkrqrw0pLsxei2RsU1V+r3dty5YMDavWabBBkb5mEC9gQQ1LpPeHsLAFXxs6SXnahmZN6p9gj+yhWBnARXis7KFalMnXOyfa7PFAGmjT+rodtHy3B5CZLxcuN9wKFgDFtgrMc9xgsPN3fZEmloJKkmfGjHuGlNd0KACJFdZ16Y1pYl5AOoo0M6psyl+V1/13PSRPFxl88sOMfeyK3DbPUzF18zJ4EwQHxChJQr2oycvJl4ZhjoZ/6ivkaADySLZj0snXAbG5Rzch9lqwb/JkKbwAygXVwikCcT6YhQs5MjEbSQ1ZON0Pm2lPCH4IfP24dpraNlCn61YqGJR37WcWcGRlf+jlnjslJuJbynFlfqzzc1Blwm8DVV3hj4TfxwKSA5pba2ZHPR8TuV41pmfdLi4kOB0FZr+x8t0SdL2qHIPkCtQZ1/k/MCaTwUvS4SuURfeDI2b5Kbr7Eaoez0jdyE6jBRUhFP6Vehx22ZO5xbCsQ0pLXZdOSG8gRqHdp9b59mJgTZrx/Lycjrfy7VJzCM+n6MN4YHw8Vc5c5SHlH8XuJbUQkyjZdEFsGASHtzmq+LmZHIJ+GIbXxK9GWLXjG/3cePMXMrIuis9kHstpo1GLWHcOLVkQeZHyY8eo1iJrKKejT8LJ7/E2SzZwpZYl+9sCgKTr3e0="

     # NEXUS_PASSWORD=...
     - secure: "shZn2O8e9Cal6ZgzIRopKQuQXVP1DTf6MYm8/Llgh9RoN7jfzPzATYoKNcXaSWXCRpwGB8Uo4soDZovlfagCRueCY6D0/kymo+UqYo+Y1/8eylYbwd3fBGVuyorYNENxMiuqxIp2DDRq1i41bk3h3R4q5of+D+ZgRQUhCFUUrizga+zomuHq0uMBBJaVf9Ze2Bjg8YH+vXgd37fGgO4MxIsK4M9GsNsOrKkK0qEqAf8zvlsM16YIvcSFXWUi9V9htTNmXzbJiNKfvyKFnP+1YqgFwivFrYYdB8iDXlVAfYKslNZq85CQNG4q54rlNOloKZUdX5rsCP2+bPtLvWa7FpGPqN2KOYC5UcCwpIhBnG82gzM0e2YpIlo1p0PHWp9RgkzivmSiJLwRSUZKrWC2xq07wVS5y/CaPZx5nsAhVgSHJv2msc6AT6Pp5x+4xMtttrsh3IZ6EvO1AoDpoZ7ujJX5Hv+kC7VN0jGFkrhmyoRUyC7ntcqzJiKx80US+Uax4vpParPtVchDxO/kEcWRdOOah5NiIe8x+xu3ehxcPur4nAKrhU93oIoq3VhVeH+HvIFkHAq8lSlqjvl1HMrjbSVh8Shh+TQ0pv/srJp07L2zEIn0b5YGNQ+D0eNTbi5TtHOmSQGYr6VQfMFFiwydrBUNv15wJ5F+LfDftOA5qPA="

     # AZ_SERVICE_PRINCIPAL=... AZ_CLIENT_SECRET=... AZ_TENANT=...
     - secure: "qikLebpdlIdCRq4fGnC/EHzjSA9ZytjDAb38+q7Zly9Dzp27iLRIa3VZhmIT2yJ13aRvps14OqceY1sfbFtt6uzkoD42wTvMNbnbv4wqWtc676SkNt/1rppj9+aRpbuUGYa+D2VmBWrLPfEaIHSxYu5mg/l6js8SgCGbLhOCuhX3ZzrfwH8U7m8fq5ROJz3RBizdnGtTB1okrA6O/cdCVdR/1WoUyu0FJDvj1wEjc7EWSSlipm/GE+rYeKg1iQxqUF1+H9K/G5gQ8xNUCr+lJIHgnx+IO7o07Pt0buDik8S4hSoe57V3QeU1oAvfbpmubz9pSW4BsDOIzITbenZx+BQUbcpGxmtx4YU2lW6jmIgSE10D35hWBbPeoaOxDm1pPtGNKp4w1j+3XExdT7/j/OSEA/EhKh59nnP8J7qmGZrs1z68q6d50Dq+m9SxFRrG0bIHMO9NKrd5J7gnva2pnixQFkXeMr3/OK1ktmamf11a66OyGN+2WylbvP8n1CTK4RCmp6GOtLw4mjck1CDN0Jqq/DSW4gLU6VcmyJkSFLOksXAcTB+KhB/Z+yBX0bEskV9VyIeXryuzVnbqE36jJ5bLZUAU/9tsyiAmHuI9hc5pz2o+fu3Dje/zYZyqB7jMsuA9vZBMyNnpo+scunS7/ZD+5IvY+7l95Blu8xbiArc="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.cache

before_install:
  - nvm install $NODE_VERSION
  - export KUBE_CONFIG_ENC_KEY=$encrypted_5162cfbd2a53_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_5162cfbd2a53_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - 'if [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE" ; fi'
  - 'if [[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=demo DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE" ; fi'
  - export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
  - source ./ci/setup_env.sh
  - 'if [[ "$SHOULD_RELEASE" ]]; then export OIDC_AUTH_VERSION=$VERSION; fi'
  - 'if [[ "$SHOULD_RELEASE" ]] ; then export NEED_INTERNAL_HELM=1 ; fi'

jobs:
  include:
    - stage: build
      name: Build projects
      install:
      - ci/gcp/install.sh
      - ci/gcp/login.sh
      script:
      - .travis/build.sh projects/jupyterhub-hub
      - travis_wait 60 .travis/build.sh projects/jupyterhub-singleuser
    - stage: build
      cache: false
      name: Build helm charts
      install:
      - source charts/.travis/install.sh
      script:
      - charts/.travis/build.sh
    - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      cache: false
      stage: Versioning
      name: Set tag and update version
      script:
      - "ci/versioning/add_tag_to_git.sh"
      - "ci/versioning/set_next_version.sh"
    - stage: deploy
      cache: false
      if: branch IN (env(RELEASE_BRANCH), env(SNAPSHOT_BRANCH)) AND type != pull_request
      install:
        - source charts/.travis/install.sh
      script:
      - travis_wait ci/helm/deploy.sh $DEPLOY_TARGET

notifications:
  slack:
    rooms:
     - secure: "xujLTGH8Vsmm3HDs02/utkTjhV+X4PY0FLOPdDUg0A38RZRgtQ+TeKerZmVBivK958e1KzsL/wPhTdeOHm7DJnanvWs1Jkw3mgbrHcaiagGjBdaEW8F30f2nsIibGWGDqzUZd5ifXYSugLNpJSpdFkVOseuWhUyTwjwrb4Ec/U/D24YvZUwX/kfi/waly57iFkxIkhq2XwcvtJtEDAzsKPhfwL67giV0flbGvCRL4xkvHERSr/HsXJ+V2NCaJ/qiSm8NkWq5gsrIIRkAA3mBSDs5Uq1ozAEI/DxN752O/OReghvjd249AEhzqJ0Ezyu0BjX3kYR1bP3gKB2/wOrLv069tAchY+KQF2F6Jh3AzGAEh0x5ARMsOxDkJybz5nXwMoYwsUjN9zGo8j9egbzkkxoVTK+MOf34jaSn7UBwAT239MaXB4Er1srJEZRqIzXVH0qwc/lC1QYX0fA89a5GdFjyN7EhfdlsvIp93nn8sjgj9iYsqS3yQboGBOSou1sboR8U/RsjPQowOkqMv8XIcjTUodirKNiRSdo5Wf+nGl4fgc3AS7rJcRaPLpbAvJZtXJzi4tutbU293q2k+bfvXbNz8R4IG7R4+MGdMWeSWDd9A0UBHgQkpXkb8Oxzr7PDAyDvhVEI5KewVy1PnV7dMCeRzSASjXTfPNnYpgBMw3E="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
