dist: focal

language: java

env:
  global:
     - APPNAME="jupyter"
     - ORG="fairspace"
     - ARTIFACT_BUILD_FILE=""
     - BUILD_SCRIPTS_REPO="thehyve/fairspace-build-scripts"
     - DEPLOYMENT_CONFIG_REPO="thehyve/fairspace-config-private"
     - ACCOUNT_CONFIG_DIR="./.travis"
     - RELEASE_BRANCH="master"
     - SNAPSHOT_BRANCH="dev"
     - DOCKER_USERNAME="fairspace"
     - GITHUB_USERNAME="fairspace-ci"
     - NEXUS_USERNAME="travis-fairspace"
     - GIT_TAG_FILES_OVERRIDE="charts/jupyter/Chart.yaml charts/jupyter/values.yaml projects/"
     - SHOULD_DEPLOY=false
     # DEPLOYMENT RELATED VARIABLES - REQUIRED IF SHOULD_DEPLOY=true
     # - GCP_PROJECT="fairspace-207108"
     # - SNAPSHOT_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     # - SNAPSHOT_CLUSTER_NAME="fairspacecicluster"
     # - SNAPSHOT_CLUSTER_ZONE="europe-west1-b"
     # - RELEASE_CONTEXT="gke_fairspace-207108_europe-west1-b_fairspacecicluster"
     # - RELEASE_CLUSTER_NAME="fairspacecicluster"
     # - RELEASE_CLUSTER_ZONE="europe-west1-b"

     # DOCKER_PASSWORD=
     - secure: "rINH6k9VSyv0N2vmle6xtT9gB3eSilSVsAmHRln4qkLTWHjLW7jjouehqFiRrdrnzFP+NIaAUdvP6ox3MhtZEFpW/pog0fZSMijpidlsHr9uCbsxhrGXjcZuzwtazaqQ/7+9RP+ofb7j6tPqt5HLCwn0pviom4qc9GztTahJwg9uNa6naiCWqIAkn7w5yqcPQZp6sgjcMYF+pKL6OQHywGp07qatozgqYkZGjtBD7QOKfNDNycVewtMQwI+CIno1/STk9kS0lECfIabETVYwt9Hzjk6811NFAwdKWVrgG+1MOU59uJC/CVbEpEfY/m1vWneWJ68L+DyYlcvzY2/pVC2A+T0L0YzhdiFCQC2xr81ODq7AQ0Y4KdYYrnewP8vJhD2zoJmfucdLpX0f93Q9k1oTd9I3sVbNK+J28N8PE6rc72t1uUA6Tzvht+OyJo5W+h4vm8zs0aWIFVLR6r0ShmindyBI0CFi6VbrvxMTNmzH1PM23oLCs3V66CTiHBBlmxEYud99zLt97/WW74DSju17wosPR9O1G2FlVPlRdhF1S7ELCN1WlFgwll7Ssy5Nk/jWqNK004+Ked3g676a38plphuOQLRKSFD7L1rh4tXli09/xjq8AXBjzyWVEUPHVFnKmDZMcQlixBVuO1FhpS6uFDLOzF6N2bfJkR8lwqI="

     # GITHUB_PASSWORD=....
     - secure: "f0vVPY7oVWXLq+TpLHDwdiTZDPvwbf2dwyabkf/dtp1qAAIqp0fYheGiNVD/sUvfyWepft763BEEJ7xbiV8VaUU8ee4xZTITo4T6xIzYcs4qkBhKIOXG3FAkQP9FrskbkYxsKWR8xLnnQkIcTOaWagPh/yiuZOGErNezKgHIh0/t3WLgZOTmQc7YT0V8FCXzO5TSQTeyR6DPi/7/kni0Q/I+GE68VTccVYGkeCpadOcam3CR7ycEHhKZbXtgvAubq64WQ+Y13hQwP5MXEf5ePNAT3P38DyVk1ObtveGbbZPUoDxeRR4jWP9bPJJAJtO6o5JFLnbdXuqjVfrgX9vAMirIoeoA0ti677faMCSQXr4ioFe/ZPdR84eL/8VN0Ciu+QRG/U2ursGkaW7FfP8XpFEdHFkSw+BDLtJaGwtqP925TrYw05HBjXEwV2w0chysaufBN5ppPLIUuEkSse2pmXN0aEfg10t1IrqXOG0fqiIb5tnbq0hii1lpuNc7VSw0UrLGqMJQjuwflAcHCQvCrlBjnMbErPs0CXWLmK5MY1wUvchEHuWy1rLDvVzjCcXpW2dTHMvY8xe1VX9Pyim/qzQMR4UHUv6A3SlqZmOlqXHJP6NWT7B73QhLitsWeRVd3I/wCfN+DnAdDC/rB/DuPP/vfDb1z/SGFi7XyoSLrGA="

cache:
  directories:
  - $HOME/downloads
  - $HOME/.cache

before_install:
  - export KUBE_CONFIG_ENC_KEY=$encrypted_f973873e750b_key
  - export KUBE_CONFIG_ENC_IV=$encrypted_f973873e750b_iv
  - git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$BUILD_SCRIPTS_REPO ci
  - export BUILD_SCRIPTS_DIR=$(pwd)/ci
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]]; then git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$DEPLOYMENT_CONFIG_REPO ci-config ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]]; then export DEPLOYMENT_CONFIG_DIR="$(pwd)/ci-config/fairspace-jupyter" ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]] && [[ "$TRAVIS_BRANCH" = "$SNAPSHOT_BRANCH" ]]; then export ALLOW_SNAPSHOTS=1 DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$SNAPSHOT_CONTEXT" CLUSTER_NAME="$SNAPSHOT_CLUSTER_NAME" CLUSTER_ZONE="$SNAPSHOT_CLUSTER_ZONE" ; fi'
  - 'if [[ "$SHOULD_DEPLOY" = "true" ]] &&[[ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" ]]; then export DEPLOY_TARGET=ci DEPLOY_PLATFORM="GCP" KUBERNETES_CONTEXT="$RELEASE_CONTEXT" CLUSTER_NAME="$RELEASE_CLUSTER_NAME" CLUSTER_ZONE="$RELEASE_CLUSTER_ZONE" ; fi'
  - export INFRASTRUCTURE_PLATFORM="${DEPLOY_PLATFORM:-NONE}"
  - source ./ci/setup_env.sh
  - 'if [[ "$SHOULD_RELEASE" ]] ; then export NEED_INTERNAL_HELM=1 ; fi'

jobs:
  include:
    - stage: build
      name: Build projects
      install:
      - ci/gcp/install.sh
      - ci/gcp/login.sh
      script:
      - .travis/build.sh projects/jupyterhub-hub
      - travis_wait 60 .travis/build.sh projects/jupyterhub-singleuser
    - stage: build
      cache: false
      name: Build helm charts
      install:
      - source charts/.travis/install.sh
      script:
      - charts/.travis/build.sh
    - if: branch = env(RELEASE_BRANCH) AND type != "pull_request"
      cache: false
      stage: Versioning
      name: Set tag and update version
      script:
      - "ci/versioning/add_tag_to_git.sh"
      - "ci/versioning/set_next_version.sh"
    - stage: deploy
      cache: false
      if: env(SHOULD_DEPLOY) = true AND branch IN (env(RELEASE_BRANCH), env(SNAPSHOT_BRANCH)) AND type != pull_request
      install:
        - source charts/.travis/install.sh
      script:
      - travis_wait ci/helm/deploy.sh $DEPLOY_TARGET

notifications:
  slack:
    rooms:
     - secure: "eeFtXTWqUURPcxfyV1FB1Qkud41rx441uka1zCEfStHNCVItoGqEvlS22lyQhk4cl7vEdnl378i+UlXFgWWzuaYIEGL9JTa7+WErfigCjYSkLIujC2bciG02TOhHYe2Pq7PhkyA8gcs3uq89ytuRUTOiy/CIvyS2GbEQrsfxNJU1C5rY5XmOeMIhTRUUF44c4ohGh4QgAHvzynk033hOMuPyQrQUpd4uKhzy3saPtYAa+uPsvqojAryvwAnfojeY8qdtAesVKkF+XBA1i0FLIRt6W4XAp3N4KodwZ9uTUelC8RGgKrB3bdad4Gbe+5n+knd6Zhci1SbhV2l94u1g00obGlETh4QAv6x++zrCqS922pkPMWFY4A7NGInyynT3Hi484UBU1Z6h+2vjjJYj28OF7M79pIoR+zzIysco5xwXaH51U1ZJKfBzzJFKSKR104rwIM0X43l6v+/RLPOPL6MNJQ1TVFSdSonyJ7IWoF63n7PrxYgA4aaySrbTr9bZpM5XXikybwZGPAejeuHTmS0Vb+ge56v4SlF3zJ/9t7Kznp54rtrdnOV8g2Sf/pMmuAAeLlxN8YtymLdS6bk8QhTqBhJkP7eOkDTO13n9DVDYcMUTAn9EJ4tIyXUJRqXPgqvG4TmVLwb/BNOFey5Y4+W0DaY4nsC/JJiHttDzibs="
    template:
     - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}"
     - "Latest commit: %{commit_message} - by %{author}"
     - "Result:  %{result} in %{duration}"
