# Default values for jupyter-fairspace.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
imagePullSecrets: {}

keycloak:
  baseUrl:
  loginRealm:
  realm:
  username:
  password:

# Setup ingress for workspace components
ingress:
  enabled: true
  domain:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10g
  tls:
    enabled: true
    secretNameOverride:
    certificate:
      obtain: true
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer

#####################################################################
# Specific settings for JupyterHub subchart
#####################################################################
jupyterhub:
  hub:
    image:
      name: eu.gcr.io/fairspace-207108/jupyterhub-hub
      tag: RELEASEVERSION
    extraEnv:
      JUPYTERHUB_CRYPT_KEY:
    config:
      JupyterHub:
        authenticator_class: oauthenticator.fairspace.FairspaceOAuthenticator
        shutdown_on_logout: true
      KubeSpawner:
        cmd: /start
        privileged: true
      RequestHandler:
        redirect_to_server: false
      FairspaceOAuthenticator:
        login_service: Fairspace
        auto_login: false
        enable_auth_state: true
        username_key: preferred_username
        client_id:
        client_secret:
        token_url:
        userdata_url:
        logout_redirect_url:
        scope:
        - offline_access
        - openid
    # Requests values are set in Jupyterhub chart.
    resources:
      limits:
        cpu: 200m
        memory: 512Mi

  singleuser:
    image:
      name: eu.gcr.io/fairspace-207108/jupyterhub-singleuser
      tag: RELEASEVERSION
    defaultUrl: "/lab"
    extraEnv:
      TARGET_URL:
      ANALYSIS_EXPORT_TARGET:
      EXTERNAL_TARGETS:
    cpu:
      limit: 0.5
      guarantee: 0.1
    memory:
      limit: 1G

  proxy:
    chp:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 200m
          memory: 512Mi
    # The JupyterHub chart requires this value to be set here with the same
    # length as the actual values
    # Ensure to override this value with a 64-character hex string when installing
    secretToken: "0000000000000000000000000000000000000000000000000000000000000000"

  scheduling:
    userScheduler:
      enabled: false
      pdb:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false

  prePuller:
    resources:
      requests:
        cpu: 0
        memory: 0
    hook:
      resources:
        requests:
          cpu: 0
          memory: 0

  ingress:
    enabled: false

  rbac:
    enabled: true

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: {}
