{{- if .Values.configurationScripts.keycloak.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-keycloak-config-map"
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
data:
  redirect.urls: |-
    {{ template "jupyter.url" $ }}/*
{{- end -}}
