version: '3'
services:
  keycloak:
    image: jboss/keycloak:4.6.0.Final
    volumes:
      - ".:/pr"
    networks:
      - local-development
    environment:
      KEYCLOAK_USER: "keycloak"
      KEYCLOAK_PASSWORD: "keycloak"
    ports:
      - "5100:8080"

  keycloak-config:
    image: eu.gcr.io/fairspace-207108/keycloak-configuration:0.1.2
    networks:
      - local-development
    environment:
      KEYCLOAK_PASSWORD: "keycloak"
      TESTUSER_USERNAME: "test"
      TESTUSER_PASSWORD: "test"
      COORDINATOR_USERNAME: "coordinator"
      COORDINATOR_PASSWORD: "coordinator"
      CLIENT_SECRET: 00000000-0000-0000-0000-000000000000
    volumes:
    - ".:/config"
    command:
      - "/config/keycloak/run-config.sh"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    networks:
      - local-development
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true"
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  local-development:
